name: Windows Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # الخطوة 1: التحقق من الكود
    - name: Checkout code
      uses: actions/checkout@v3

    # الخطوة 2: إعداد Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # الخطوة 3: ترجمة الكود
    - name: Compile Windows Project
      run: |
        mkdir -p windows/out
        javac -d windows/out windows/*.java shared/*.java

    # الخطوة 4: تشغيل الاختبارات (إن وجدت)
    - name: Run Tests
      run: |
        echo "No specific tests available. Add your test commands here if needed."
